### ISSUE TITLE
Comparing images of different size

### ISSUE THREAD

**Issue by tomrozb** [limonadev/diff_image#2]
First it's a really great library!
 
In my use case I need to compare images of different size. I'd like to have one image of given size, and be able to check different images (of different size) for similarity.

This can be done by scaling the image before passing it to compare method, but right now it works only with web links, so I don't really can do this.

Is scaling in library possible and easy to implement?

**Comment by limonadev** [comment]
The package now supports receiving Images from local memory apart from URLs. Solved on the [last version](https://github.com/limonadev/diff_image/commit/9516e78a309642b2bff08cd2121cef5253f4a5f6).
