### ISSUE TITLE
Support images in memory 

### ISSUE THREAD

**Issue by kenthinson** [limonadev/diff_image#3]
Support for using images in the application memory would be great. For example I see another issue on here where they want to compare images of different sizes. This could be accomplished easily if we can manipulate the image first in ram before passing to this package.

**Comment by Ram121** [comment]
Please provide support for using images from memory

**Comment by limonadev** [comment]
The package now supports receiving Images from local memory apart from URLs. Solved on the [last version](https://github.com/limonadev/diff_image/commit/9516e78a309642b2bff08cd2121cef5253f4a5f6).
