### ISSUE TITLE
Image conflicting with Image from different packages and showing error  Index out of range: index should be less than

### ISSUE THREAD

**Issue by Ram121** [limonadev/diff_image#4]
First of all thanks for providing new feature of compareFromMemory
When using diff_image package it is conflicting with Image from different class like material and Image class, also it is showing error of  Index out of range: index should be less than 17681: 17760, please help

Following is the code I am using

  getPictureDirectory() async {
    directory = await getApplicationDocumentsDirectory();
    return '${directory.path}/pictures';
  }

  getDirectories() async {
    getPictureDirectory();
    File pickedImageComp = File('$dirPath/componentImage.jpg');
    imageBytesComp = pickedImageComp.readAsBytesSync();
    File pickedImageMast = File('$dirPath/masterImage.jpg');
    imageBytesMast = pickedImageMast.readAsBytesSync();
    imageComp = Image.file(File('$dirPath/componentImage.jpg'));
    imageMast = Image.file(File('$dirPath/masterImage.jpg'));
    decodedImageComp = await decodeImageFromList(pickedImageComp.readAsBytesSync());
    decodedImageMast = await decodeImageFromList(pickedImageMast.readAsBytesSync());
  }

  calculateDifference() async {
    await getDirectories();
    var firstImageFromMemoryComp =
        compImage.Image.fromBytes(decodedImageComp.width.toInt(), decodedImageComp.height.toInt(), imageBytesComp);
    var secondImageFromMemoryMast =
        compImage.Image.fromBytes(decodedImageMast.width.toInt(), decodedImageMast.height.toInt(), imageBytesMast);
    DiffImgResult diff = DiffImage.compareFromMemory(
      firstImageFromMemoryComp,
      secondImageFromMemoryMast,
      asPercentage: true,
    );
    print('The difference between images is: ${diff.diffValue} percent');
  }

Thanks

**Comment by limonadev** [comment]
Please provide a reproducible code or repository to check the issue.

**Comment by Ram121** [comment]
Following is the link to repository, please check

https://github.com/Ram121/ImageCompare

**Comment by limonadev** [comment]
The `image` package conflict is solved with the last update. With respect to the Index error, I want to know if you can send me the two images you are using to compare. This way I can test only the package functions with the same images you are using.

**Comment by Ram121** [comment]
I have uploaded the file in above source, the same image I am using as master also, for testing,

https://github.com/Ram121/ImageCompare/blob/master/componentImage.jpg

Edit: I checked with Android virtual device also, it is showing index error for android virtual device also, I was thinking it is because of bigger size of image taken by phone camera but doesn't seems like that

**Comment by limonadev** [comment]
I was unable to reproduce the bug.
I tested the provided image on a simple project: the package is correctly returning the difference. You can test it by using the [example](https://github.com/limonadev/diff_image/tree/main/example) project in this repo, replace the path of the `imageFromMemory` variable to use the `componentImage.jpg`, and you will see the package is working flawlessly.

**Comment by Ram121** [comment]
> I was unable to reproduce the bug.
> I tested the provided image on a simple project: the package is correctly returning the difference. You can test it by using the [example](https://github.com/limonadev/diff_image/tree/main/example) project in this repo, replace the path of the `imageFromMemory` variable to use the `componentImage.jpg`, and you will see the package is working flawlessly.

I will check and reply, thanks

**Comment by Ram121** [comment]
@limonadev tried with your given example, now found working perfectly, thank you very much for your support
